name: Pipeline_Operacao_CI

on: [push]

jobs:
  executar-testes:
    runs-on: ubuntu-latest

    steps:
      - name: Baixando o Código
        uses: actions/checkout@v4

      - name: Instalando o Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalando Dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Teste - PetStore Swagger
        run: python PetStore_Swager_Teste/main.py
        working-directory: PetStore_Swager_Teste

      - name: Teste - Automação Sauce
        working-directory: automacao_sauce
        run: python automacao_sauce/main.py
        env:
          SAUCE_USERNAME: ${{ secrets.SAUCE_USERNAME }}
          SAUCE_PASSWORD: ${{ secrets.SAUCE_PASSWORD }}
          SAUCE_NOME: ${{ secrets.SAUCE_NOME }}
          SAUCE_SOBRENOME: ${{ secrets.SAUCE_SOBRENOME }}
          SAUCE_CEP: ${{ secrets.SAUCE_CEP }}
          SAUCE_ORCAMENTO: ${{ secrets.SAUCE_ORCAMENTO }}